version: "3"

services:
  
  fm-cache:
    image: redis:7
    volumes:
      - ./fm_redis_data/:/data/
    restart: unless-stopped

  form-manager:
    image: form-manager
    build: packages/form-manager
    depends_on:
      - fm-cache
      # - minio
      # - createbuckets
    ports:
      - 3006:3006
    environment:
      MINIO_USERNAME: ${MINIO_USERNAME}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_PORT: ${MINIO_PORT}
      MINIO_URL: ${MINIO_URL}
      MINIO_PASSWORD: ${MINIO_PASSWORD}
      MINIO_BUCKETNAME: ${MINIO_BUCKETNAME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      FORM_MANAGER_URL: ${FORM_MANAGER_URL}
      MINIO_USE_SSL: ${MINIO_USE_SSL}
      GCP_BUCKET_NAME: ${GCP_BUCKET_NAME}
      GCP_PROJECT_ID: ${GCP_PROJECT_ID}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
